// - rlyeh

#include <wire/wire.hpp>
#include <wire/wire.cpp>

#include <sao/file.hpp>
#include <sao/file.cpp>

int main( int argc, char **argv )
{
	wire::strings args( argc, argv );

	for( auto &arg : args ) {
		sao::file file( arg );

		if( !file.size() )
			continue;

		wire::string data = file.read(), outdata;
		wire::string filename = wire::string( file.name() ).lowercase().replace(".","_").replace("-","_");

		outdata << wire::string(
			"// generated by b2hpp\n"
			"#pragma once\n"
			"\n"
			"namespace \1\n"
			"{\n"
			"\textern const size_t size();\n"
			"\textern const void * data();\n"
			"}\n"
			"\n",
			filename );

		sao::file( file.name() + ".hpp" ).overwrite( outdata );
	}

	return 0;
}
